{% set name = "dim" %}
{% set version = "20.32" %}
{% set manualversion = "v20r32" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: http://dim.web.cern.ch/dim_{{ manualversion }}.zip
  sha256: c64636232511925774c70710dac3cb09ccc9c7b6ec984538a44ace5a6a6c533f

build:
  script_env:
    - OS=Linux
    - ODIR=linux
    - DIMDIR=.
  number: 0
  skip: true  # [win or osx]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - glib

test:
  commands:
    - dns -h

about:
  home: https://dim.web.cern.ch
  license: GPL-2.0-or-later
  license_family: GPL
  summary: DIM is a communication system for distributed/mixed environments, it provides a network transparent inter-process communication layer
  license_file: LICENSE.GPL


extra:
  recipe-maintainers:
    - chaen
