{% set name = "pydim3" %}
{% set version = "3.0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://gitlab.cern.ch/lhcb-online/pydim/-/archive/main/pydim-main.tar.gz
  sha256: 831fc2e9eedca892f6a223365ac8ec392925328192ccf6b242c12b46594e7d6f

build:
  skip: true  # [win or osx]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make 
  host:
    - pip
    - python
    - dim
  run:
    - python

test:
  imports:
    - pydim

about:
  home: http://lhcbdoc.web.cern.ch/lhcbdoc/pydim/index.html
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE.GPL
  summary: Python interface package for DIM C and C++ interfaces.

extra:
  recipe-maintainers:
    - chaen
